language: python

env:
    - TOX_ENV=py27
    - TOX_ENV=py32

matrix:
    exclude:
        - env: TOX_ENV=py32

install:
    - pip install --upgrade setuptools
    - pip install --upgrade babel
    - pip install tox

script:
    - tox -e $TOX_ENV
